language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install "coverage<4.4" "pytest-cov<2.5" codeclimate-test-reporter black
  - pip install .

script:

  - export PYTHONPATH='.'
  - pytest --cov=bilbywave
  - codeclimate-test-reporter --file .coverage
  - black --py36 --diff bilbywave
